name        : python-mpd
version     : 0.3.0
release     : 1
homepage    : https://pypi.python.org/pypi/python-mpd
source      :
    - https://pypi.python.org/packages/source/p/python-mpd/python-mpd-0.3.0.tar.gz : 02812eba1d2e0f46e37457f5a6fa23ba203622e4bcab0a19b265e66b08cd21b4
license     : GPL-3.0
summary     : Python MPD client library
description : |
    Python MPD client library
install     : |
    python2 setup.py install --root="$installdir" --optimize=1
